// Copyright (c) 2026 The Rincoin developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.
//
// Signature-hash rules of the height-840,000 transition (SIGHASH_FORKID, fork ID 840):
//  - the constants, as implementers see them;
//  - known-answer vectors generated by test/util/gen_s6b_sighash_vectors.py, an
//    independent hashlib-only implementation (the expected digests do not come from
//    the code under test);
//  - signatures of real Bitcoin Gold main-chain transactions, which verify when the
//    same code runs with Bitcoin Gold's fork ID and with no other;
//  - how the digest depends on the regime, the flag, the fork ID and the amount;
//  - the consensus rule that every evaluated signature must set SIGHASH_FORKID, through
//    VerifyScript() for CHECKSIG, CHECKSIGVERIFY, CHECKMULTISIG and CHECKMULTISIGVERIFY,
//    including the OP_NOT forms, and that nothing changes below the transition height;
//  - SIGHASH_SINGLE without a matching output on both sides of the transition.

#include <chainparams.h>
#include <consensus/sigforkid.h>
#include <core_io.h>
#include <key.h>
#include <pubkey.h>
#include <script/interpreter.h>
#include <script/script.h>
#include <script/script_error.h>
#include <script/standard.h>
#include <streams.h>
#include <test/data/s6b_sighash.json.h>
#include <test/util/setup_common.h>
#include <util/strencodings.h>
#include <version.h>

#include <univalue.h>

#include <boost/test/unit_test.hpp>

#include <string>
#include <vector>

extern UniValue read_json(const std::string& jsondata);

namespace {

/** Consensus script flags of a current mainnet block (no policy-only flags such as NULLFAIL or STRICTENC). */
const unsigned int CONSENSUS_FLAGS = SCRIPT_VERIFY_P2SH | SCRIPT_VERIFY_DERSIG | SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY |
                                     SCRIPT_VERIFY_CHECKSEQUENCEVERIFY | SCRIPT_VERIFY_WITNESS | SCRIPT_VERIFY_NULLDUMMY;

const std::vector<int> BASE_HASH_TYPES{SIGHASH_ALL, SIGHASH_NONE, SIGHASH_SINGLE,
                                       SIGHASH_ALL | SIGHASH_ANYONECANPAY, SIGHASH_NONE | SIGHASH_ANYONECANPAY, SIGHASH_SINGLE | SIGHASH_ANYONECANPAY};

std::vector<unsigned char> SignDigest(const CKey& key, const uint256& digest, int hash_type)
{
    std::vector<unsigned char> sig;
    BOOST_REQUIRE(key.Sign(digest, sig));
    sig.push_back(static_cast<unsigned char>(hash_type));
    return sig;
}

/** Two inputs, one output: input 1 has no matching output. */
CMutableTransaction MakeTwoInOneOut()
{
    CMutableTransaction tx;
    tx.nVersion = 2;
    tx.vin.resize(2);
    tx.vin[0].prevout = COutPoint(uint256S("11"), 0);
    tx.vin[1].prevout = COutPoint(uint256S("22"), 3);
    tx.vout.resize(1);
    tx.vout[0].nValue = 1000;
    tx.vout[0].scriptPubKey = CScript() << OP_TRUE;
    return tx;
}

PrecomputedTransactionData Regime(bool fork_active, SigForkId fork_id = SIG_FORK_ID_840K)
{
    PrecomputedTransactionData txdata;
    txdata.SetSigForkId(fork_id, fork_active);
    return txdata;
}

struct ScriptResult {
    bool ok;
    ScriptError err;
};

ScriptResult Run(const CScript& script_sig, const CScript& script_pubkey, const CMutableTransaction& mtx, unsigned int n_in, bool fork_active,
                 const CScriptWitness* witness = nullptr, CAmount amount = 0, unsigned int flags = CONSENSUS_FLAGS, SigForkId fork_id = SIG_FORK_ID_840K)
{
    const CTransaction tx(mtx);
    const PrecomputedTransactionData txdata = Regime(fork_active, fork_id);
    TransactionSignatureChecker checker(&tx, n_in, amount, txdata);
    ScriptError err = SCRIPT_ERR_UNKNOWN_ERROR;
    const bool ok = VerifyScript(script_sig, script_pubkey, witness, flags, checker, &err);
    return {ok, err};
}

/** A signature of `key` that is valid for this input on the given side of the transition. */
std::vector<unsigned char> ValidSig(const CKey& key, const CScript& script_code, const CMutableTransaction& tx, unsigned int n_in, int base_hash_type,
                                    bool fork_active, CAmount amount = 0, SigVersion sigversion = SigVersion::BASE)
{
    const int hash_type = fork_active ? (base_hash_type | SIGHASH_FORKID) : base_hash_type;
    const PrecomputedTransactionData txdata = Regime(fork_active);
    return SignDigest(key, SignatureHash(script_code, CTransaction(tx), n_in, hash_type, amount, sigversion, &txdata), hash_type);
}

} // namespace

BOOST_FIXTURE_TEST_SUITE(s6b_sighash_tests, BasicTestingSetup)

BOOST_AUTO_TEST_CASE(fork_id_constants)
{
    BOOST_CHECK_EQUAL(SIGHASH_FORKID, 0x40);
    BOOST_CHECK_EQUAL(SIG_FORK_ID_840K, 840U);
    BOOST_CHECK_EQUAL(SIG_FORK_ID_840K, 0x000348U);
    // Not zero (SegWit v0 signatures would verify under the historical rules as well),
    // and small enough for the shifted value to be positive in a signed 32-bit integer.
    BOOST_CHECK(SIG_FORK_ID_840K != 0);
    BOOST_CHECK(SIG_FORK_ID_840K < (1U << 23));

    // What ends the preimage of a SIGHASH_ALL signature: 41 48 03 00.
    const uint32_t hash_type_field = (SIGHASH_ALL | SIGHASH_FORKID) | (SIG_FORK_ID_840K << 8);
    BOOST_CHECK_EQUAL(hash_type_field, 0x00034841U);
    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
    ss << hash_type_field;
    BOOST_CHECK_EQUAL(HexStr(ss), "41480300");
    // The value other software is configured with when it takes "flag and fork ID" as one number.
    BOOST_CHECK_EQUAL(SIGHASH_FORKID | (SIG_FORK_ID_840K << 8), 0x00034840U);

    // Identical on every network; only the activation height differs.
    for (const std::string& chain : {CBaseChainParams::MAIN, CBaseChainParams::TESTNET, CBaseChainParams::REGTEST, CBaseChainParams::PREVIEW}) {
        const auto params = CreateChainParams(*m_node.args, chain);
        BOOST_CHECK(params->GetConsensus().sigForkId == SIG_FORK_ID_840K);
    }
    BOOST_CHECK_EQUAL(CreateChainParams(*m_node.args, CBaseChainParams::MAIN)->GetConsensus().nS6bHeight, 840000);
    BOOST_CHECK_EQUAL(CreateChainParams(*m_node.args, CBaseChainParams::TESTNET)->GetConsensus().nS6bHeight, 8400);
    BOOST_CHECK_EQUAL(CreateChainParams(*m_node.args, CBaseChainParams::REGTEST)->GetConsensus().nS6bHeight, 840);
    BOOST_CHECK_EQUAL(CreateChainParams(*m_node.args, CBaseChainParams::PREVIEW)->GetConsensus().nS6bHeight, 840);
}

BOOST_AUTO_TEST_CASE(known_answer_vectors)
{
    const UniValue entries = read_json(std::string(json_tests::s6b_sighash, json_tests::s6b_sighash + sizeof(json_tests::s6b_sighash)));

    unsigned int vectors = 0;
    for (unsigned int i = 0; i < entries.size(); i++) {
        const UniValue& v = entries[i];
        if (v["kind"].get_str() != "vector") continue;
        vectors++;
        const std::string desc = strprintf("entry %u (%s, hash_type=0x%02x, input=%d, fork_active=%d)", i,
                                           v["sigversion"].get_str(), v["hash_type"].get_int(), v["input_index"].get_int(), v["fork_active"].get_bool());

        CDataStream stream(ParseHex(v["tx"].get_str()), SER_NETWORK, PROTOCOL_VERSION | SERIALIZE_TRANSACTION_NO_WITNESS);
        const CTransaction tx(deserialize, stream);
        const std::vector<unsigned char> code_bytes = ParseHex(v["script_code"].get_str());
        const CScript script_code(code_bytes.begin(), code_bytes.end());
        const unsigned int n_in = v["input_index"].get_int();
        const int hash_type = v["hash_type"].get_int();
        const CAmount amount = v["amount"].get_int64();
        const SigVersion sigversion = v["sigversion"].get_str() == "base" ? SigVersion::BASE : SigVersion::WITNESS_V0;
        const bool fork_active = v["fork_active"].get_bool();
        BOOST_REQUIRE_EQUAL(v["fork_id"].get_int(), (int)SIG_FORK_ID_840K);

        const PrecomputedTransactionData txdata = Regime(fork_active);
        const uint256 hash = SignatureHash(script_code, tx, n_in, hash_type, amount, sigversion, &txdata);
        BOOST_CHECK_MESSAGE(HexStr(hash) == v["sighash"].get_str(), desc);

        // The same with the BIP143 hashes precomputed, as block validation does it.
        PrecomputedTransactionData precomputed = Regime(fork_active);
        precomputed.Init(tx, {});
        BOOST_CHECK_MESSAGE(precomputed.m_bip143_segwit_ready == fork_active, desc);
        BOOST_CHECK_MESSAGE(SignatureHash(script_code, tx, n_in, hash_type, amount, sigversion, &precomputed) == hash, desc);

        // A caller that passes no regime gets the historical digest.
        if (!fork_active) {
            BOOST_CHECK_MESSAGE(SignatureHash(script_code, tx, n_in, hash_type, amount, sigversion, nullptr) == hash, desc);
        }
    }
    BOOST_CHECK_EQUAL(vectors, 144U);
}

// The scheme is the one Bitcoin Gold deployed. Run with Bitcoin Gold's fork ID, this
// code must accept signatures taken from its main chain, and with no other fork ID.
BOOST_AUTO_TEST_CASE(bitcoin_gold_reference_signatures)
{
    const UniValue entries = read_json(std::string(json_tests::s6b_sighash, json_tests::s6b_sighash + sizeof(json_tests::s6b_sighash)));
    const unsigned int standard_flags = CONSENSUS_FLAGS | SCRIPT_VERIFY_STRICTENC | SCRIPT_VERIFY_LOW_S | SCRIPT_VERIFY_NULLFAIL;

    unsigned int cases = 0;
    for (unsigned int i = 0; i < entries.size(); i++) {
        const UniValue& v = entries[i];
        if (v["kind"].get_str() != "bitcoin_gold") continue;
        cases++;
        const std::string desc = strprintf("entry %u (txid %s, input %d)", i, v["txid"].get_str(), v["input_index"].get_int());

        CDataStream stream(ParseHex(v["tx"].get_str()), SER_NETWORK, PROTOCOL_VERSION);
        const CTransaction tx(deserialize, stream);
        BOOST_CHECK_MESSAGE(tx.GetHash().GetHex() == v["txid"].get_str(), desc);
        const unsigned int n_in = v["input_index"].get_int();
        const std::vector<unsigned char> spk_bytes = ParseHex(v["script_pubkey"].get_str());
        const CScript script_pubkey(spk_bytes.begin(), spk_bytes.end());
        const std::vector<unsigned char> code_bytes = ParseHex(v["script_code"].get_str());
        const CScript script_code(code_bytes.begin(), code_bytes.end());
        const CAmount amount = v["amount"].get_int64();
        const SigVersion sigversion = v["sigversion"].get_str() == "base" ? SigVersion::BASE : SigVersion::WITNESS_V0;
        const SigForkId bitcoin_gold = v["fork_id"].get_int();
        BOOST_REQUIRE_EQUAL(bitcoin_gold, 79U);

        // The digest, and the signature over it.
        std::vector<unsigned char> sig = ParseHex(v["signature"].get_str());
        const int hash_type = sig.back();
        BOOST_CHECK_MESSAGE(hash_type == v["hash_type"].get_int() && (hash_type & SIGHASH_FORKID), desc);
        sig.pop_back();
        const CPubKey pubkey(ParseHex(v["pubkey"].get_str()));
        const PrecomputedTransactionData gold = Regime(true, bitcoin_gold);
        const uint256 hash = SignatureHash(script_code, tx, n_in, hash_type, amount, sigversion, &gold);
        BOOST_CHECK_MESSAGE(HexStr(hash) == v["sighash"].get_str(), desc);
        BOOST_CHECK_MESSAGE(pubkey.Verify(hash, sig), desc);

        // The whole input through the interpreter, with consensus and with standard flags.
        const CMutableTransaction mtx(tx);
        const CScriptWitness& witness = tx.vin[n_in].scriptWitness;
        BOOST_CHECK_MESSAGE(Run(tx.vin[n_in].scriptSig, script_pubkey, mtx, n_in, true, &witness, amount, CONSENSUS_FLAGS, bitcoin_gold).ok, desc);
        BOOST_CHECK_MESSAGE(Run(tx.vin[n_in].scriptSig, script_pubkey, mtx, n_in, true, &witness, amount, standard_flags, bitcoin_gold).ok, desc);
        // Not with this chain's fork ID, not with Bitcoin Cash's, and not under the historical rules.
        BOOST_CHECK_MESSAGE(!Run(tx.vin[n_in].scriptSig, script_pubkey, mtx, n_in, true, &witness, amount, CONSENSUS_FLAGS, SIG_FORK_ID_840K).ok, desc);
        BOOST_CHECK_MESSAGE(!Run(tx.vin[n_in].scriptSig, script_pubkey, mtx, n_in, true, &witness, amount, CONSENSUS_FLAGS, 0).ok, desc);
        BOOST_CHECK_MESSAGE(!Run(tx.vin[n_in].scriptSig, script_pubkey, mtx, n_in, false, &witness, amount, CONSENSUS_FLAGS, bitcoin_gold).ok, desc);
    }
    BOOST_CHECK_EQUAL(cases, 2U); // one pre-SegWit input, one SegWit v0 input
}

BOOST_AUTO_TEST_CASE(what_the_digest_depends_on)
{
    const CMutableTransaction mtx = MakeTwoInOneOut();
    const CTransaction tx(mtx);
    const CScript script_code = CScript() << OP_TRUE;
    const PrecomputedTransactionData inactive = Regime(false);
    const PrecomputedTransactionData active = Regime(true);
    const PrecomputedTransactionData other_id = Regime(true, SIG_FORK_ID_840K + 1);

    for (int base_type : BASE_HASH_TYPES) {
        const int fork_type = base_type | SIGHASH_FORKID;
        for (SigVersion sv : {SigVersion::BASE, SigVersion::WITNESS_V0}) {
            const uint256 historical = SignatureHash(script_code, tx, 0, base_type, 5000, sv, nullptr);
            const uint256 historical_with_flag_bit = SignatureHash(script_code, tx, 0, fork_type, 5000, sv, nullptr);
            const uint256 protected_digest = SignatureHash(script_code, tx, 0, fork_type, 5000, sv, &active);

            // Below the transition nothing changes, whatever the hash type byte says.
            BOOST_CHECK(SignatureHash(script_code, tx, 0, base_type, 5000, sv, &inactive) == historical);
            BOOST_CHECK(SignatureHash(script_code, tx, 0, fork_type, 5000, sv, &inactive) == historical_with_flag_bit);
            // From it, a signature without the flag is still hashed the historical way
            // (the interpreter rejects it before it gets that far) ...
            BOOST_CHECK(SignatureHash(script_code, tx, 0, base_type, 5000, sv, &active) == historical);
            // ... and one with the flag gets a digest of its own, specific to the fork ID.
            BOOST_CHECK(protected_digest != historical);
            BOOST_CHECK(protected_digest != historical_with_flag_bit);
            BOOST_CHECK(protected_digest != SignatureHash(script_code, tx, 0, fork_type, 5000, sv, &other_id));
            // It commits to the amount for pre-SegWit inputs too,
            BOOST_CHECK(protected_digest != SignatureHash(script_code, tx, 0, fork_type, 5001, sv, &active));
            // and is the same digest whatever the script version.
            BOOST_CHECK(protected_digest == SignatureHash(script_code, tx, 0, fork_type, 5000, SigVersion::BASE, &active));
        }
    }
}

BOOST_AUTO_TEST_CASE(every_evaluated_signature_must_use_forkid)
{
    CKey key, key2, other_key;
    key.MakeNewKey(true);
    key2.MakeNewKey(true);
    other_key.MakeNewKey(true);
    const std::vector<unsigned char> pubkey = ToByteVector(key.GetPubKey());
    const CMutableTransaction tx = MakeTwoInOneOut();
    const unsigned int n_in = 0;

    const CScript checksig = CScript() << pubkey << OP_CHECKSIG;
    const CScript checksigverify = CScript() << pubkey << OP_CHECKSIGVERIFY << OP_1;
    const CScript multisig = CScript() << OP_1 << pubkey << OP_1 << OP_CHECKMULTISIG;
    const CScript multisigverify = CScript() << OP_1 << pubkey << OP_1 << OP_CHECKMULTISIGVERIFY << OP_1;
    const CScript checksig_not = CScript() << pubkey << OP_CHECKSIG << OP_NOT;
    const CScript multisig_not = CScript() << OP_1 << pubkey << OP_1 << OP_CHECKMULTISIG << OP_NOT;

    for (int base_type : BASE_HASH_TYPES) {
        for (const CScript& spk : {checksig, checksigverify, multisig, multisigverify}) {
            const bool is_multisig = (spk == multisig || spk == multisigverify);
            auto script_sig = [&](const std::vector<unsigned char>& sig) { return is_multisig ? (CScript() << OP_0 << sig) : (CScript() << sig); };
            const std::vector<unsigned char> old_style = ValidSig(key, spk, tx, n_in, base_type, false);
            const std::vector<unsigned char> new_style = ValidSig(key, spk, tx, n_in, base_type, true);

            // Below the transition height: the historical signature, and only it.
            BOOST_CHECK(Run(script_sig(old_style), spk, tx, n_in, false).ok);
            BOOST_CHECK(!Run(script_sig(new_style), spk, tx, n_in, false).ok);
            // From it: the replay-protected one; the historical one is a script error.
            BOOST_CHECK(Run(script_sig(new_style), spk, tx, n_in, true).ok);
            const ScriptResult r = Run(script_sig(old_style), spk, tx, n_in, true);
            BOOST_CHECK(!r.ok);
            BOOST_CHECK_EQUAL(r.err, SCRIPT_ERR_MUST_USE_FORKID);
        }
    }

    // A script error, not a false result: OP_NOT cannot turn it into success, whoever signed.
    for (const CKey& signer : {key, other_key}) {
        const std::vector<unsigned char> old_style = ValidSig(signer, checksig_not, tx, n_in, SIGHASH_ALL, false);
        ScriptResult r = Run(CScript() << old_style, checksig_not, tx, n_in, true);
        BOOST_CHECK(!r.ok);
        BOOST_CHECK_EQUAL(r.err, SCRIPT_ERR_MUST_USE_FORKID);
        r = Run(CScript() << OP_0 << ValidSig(signer, multisig_not, tx, n_in, SIGHASH_ALL, false), multisig_not, tx, n_in, true);
        BOOST_CHECK(!r.ok);
        BOOST_CHECK_EQUAL(r.err, SCRIPT_ERR_MUST_USE_FORKID);
    }
    // What stays an ordinary failed check that OP_NOT inverts, exactly as before (NULLFAIL is
    // policy, not consensus): a replay-protected signature that does not verify, and the empty signature.
    BOOST_CHECK(Run(CScript() << ValidSig(other_key, checksig_not, tx, n_in, SIGHASH_ALL, true), checksig_not, tx, n_in, true).ok);
    BOOST_CHECK(Run(CScript() << OP_0, checksig_not, tx, n_in, true).ok);
    BOOST_CHECK(Run(CScript() << OP_0 << OP_0, multisig_not, tx, n_in, true).ok);

    // 2-of-2 multisig: both signatures have to be replay-protected ones.
    {
        const CScript two_of_two = CScript() << OP_2 << pubkey << ToByteVector(key2.GetPubKey()) << OP_2 << OP_CHECKMULTISIG;
        const std::vector<unsigned char> new1 = ValidSig(key, two_of_two, tx, n_in, SIGHASH_ALL, true);
        const std::vector<unsigned char> new2 = ValidSig(key2, two_of_two, tx, n_in, SIGHASH_ALL, true);
        const std::vector<unsigned char> old1 = ValidSig(key, two_of_two, tx, n_in, SIGHASH_ALL, false);
        const std::vector<unsigned char> old2 = ValidSig(key2, two_of_two, tx, n_in, SIGHASH_ALL, false);
        BOOST_CHECK(Run(CScript() << OP_0 << new1 << new2, two_of_two, tx, n_in, true).ok);
        BOOST_CHECK_EQUAL(Run(CScript() << OP_0 << new1 << old2, two_of_two, tx, n_in, true).err, SCRIPT_ERR_MUST_USE_FORKID);
        BOOST_CHECK_EQUAL(Run(CScript() << OP_0 << old1 << new2, two_of_two, tx, n_in, true).err, SCRIPT_ERR_MUST_USE_FORKID);
        BOOST_CHECK(Run(CScript() << OP_0 << old1 << old2, two_of_two, tx, n_in, false).ok);
    }

    // SegWit v0 (P2WSH): the same rule.
    {
        const CScript witness_script = CScript() << pubkey << OP_CHECKSIG;
        const CScript spk = GetScriptForDestination(WitnessV0ScriptHash(witness_script));
        const CAmount amount = 12345;
        auto witness_with = [&](const std::vector<unsigned char>& sig) {
            CScriptWitness w;
            w.stack.push_back(sig);
            w.stack.push_back(std::vector<unsigned char>(witness_script.begin(), witness_script.end()));
            return w;
        };
        const CScriptWitness old_style = witness_with(ValidSig(key, witness_script, tx, n_in, SIGHASH_ALL, false, amount, SigVersion::WITNESS_V0));
        const CScriptWitness new_style = witness_with(ValidSig(key, witness_script, tx, n_in, SIGHASH_ALL, true, amount, SigVersion::WITNESS_V0));
        BOOST_CHECK(Run(CScript(), spk, tx, n_in, false, &old_style, amount).ok);
        BOOST_CHECK(!Run(CScript(), spk, tx, n_in, false, &new_style, amount).ok);
        BOOST_CHECK(Run(CScript(), spk, tx, n_in, true, &new_style, amount).ok);
        BOOST_CHECK_EQUAL(Run(CScript(), spk, tx, n_in, true, &old_style, amount).err, SCRIPT_ERR_MUST_USE_FORKID);
        // The amount is part of what was signed.
        BOOST_CHECK(!Run(CScript(), spk, tx, n_in, true, &new_style, amount + 1).ok);
    }

    // Pre-SegWit inputs commit to the amount as well now.
    {
        const std::vector<unsigned char> sig = ValidSig(key, checksig, tx, n_in, SIGHASH_ALL, true, /* amount */ 777);
        BOOST_CHECK(Run(CScript() << sig, checksig, tx, n_in, true, nullptr, 777).ok);
        BOOST_CHECK(!Run(CScript() << sig, checksig, tx, n_in, true, nullptr, 778).ok);
    }
}

BOOST_AUTO_TEST_CASE(history_is_untouched_and_policy_follows)
{
    CKey key;
    key.MakeNewKey(true);
    const std::vector<unsigned char> pubkey = ToByteVector(key.GetPubKey());
    const CMutableTransaction tx = MakeTwoInOneOut();
    const CScript checksig = CScript() << pubkey << OP_CHECKSIG;
    const unsigned int policy_flags = CONSENSUS_FLAGS | SCRIPT_VERIFY_STRICTENC;

    // Below the transition height a hash type byte with bit 0x40 set means what it always
    // meant to consensus: an unusual byte that is part of the historical preimage. Such a
    // signature stays valid there (and non-standard), so no historical block changes.
    {
        const int odd_type = SIGHASH_ALL | SIGHASH_FORKID;
        const uint256 historical = SignatureHash(checksig, CTransaction(tx), 0, odd_type, 0, SigVersion::BASE, nullptr);
        const std::vector<unsigned char> sig = SignDigest(key, historical, odd_type);
        BOOST_CHECK(Run(CScript() << sig, checksig, tx, 0, false).ok);
        const ScriptResult policy = Run(CScript() << sig, checksig, tx, 0, false, nullptr, 0, policy_flags);
        BOOST_CHECK(!policy.ok);
        BOOST_CHECK_EQUAL(policy.err, SCRIPT_ERR_SIG_HASHTYPE);
        // From the transition height the same bytes are hashed the new way and no longer verify.
        BOOST_CHECK(!Run(CScript() << sig, checksig, tx, 0, true).ok);
    }

    // From the transition height STRICTENC knows the hash types with SIGHASH_FORKID,
    // and still refuses undefined ones.
    {
        BOOST_CHECK(Run(CScript() << ValidSig(key, checksig, tx, 0, SIGHASH_SINGLE | SIGHASH_ANYONECANPAY, true), checksig, tx, 0, true, nullptr, 0, policy_flags).ok);
        const int undefined_type = 0x04 | SIGHASH_FORKID;
        const PrecomputedTransactionData active = Regime(true);
        const std::vector<unsigned char> sig = SignDigest(key, SignatureHash(checksig, CTransaction(tx), 0, undefined_type, 0, SigVersion::BASE, &active), undefined_type);
        BOOST_CHECK(Run(CScript() << sig, checksig, tx, 0, true).ok); // consensus: as permissive as it always was
        BOOST_CHECK_EQUAL(Run(CScript() << sig, checksig, tx, 0, true, nullptr, 0, policy_flags).err, SCRIPT_ERR_SIG_HASHTYPE);
    }

    // The encoding check on its own.
    {
        const std::vector<unsigned char> old_style = ValidSig(key, checksig, tx, 0, SIGHASH_ALL, false);
        const std::vector<unsigned char> new_style = ValidSig(key, checksig, tx, 0, SIGHASH_ALL, true);
        ScriptError err = SCRIPT_ERR_OK;
        BOOST_CHECK(CheckSignatureEncoding(old_style, SCRIPT_VERIFY_STRICTENC, &err));
        BOOST_CHECK(!CheckSignatureEncoding(new_style, SCRIPT_VERIFY_STRICTENC, &err));
        BOOST_CHECK_EQUAL(err, SCRIPT_ERR_SIG_HASHTYPE);
        BOOST_CHECK(CheckSignatureEncoding(new_style, SCRIPT_VERIFY_STRICTENC, &err, /* sighash_forkid_active */ true));
        BOOST_CHECK(!CheckSignatureEncoding(old_style, 0, &err, /* sighash_forkid_active */ true));
        BOOST_CHECK_EQUAL(err, SCRIPT_ERR_MUST_USE_FORKID);
        BOOST_CHECK(CheckSignatureEncoding({}, 0, &err, /* sighash_forkid_active */ true)); // the empty signature
    }
}

// The historical quirk: a pre-SegWit SIGHASH_SINGLE signature for an input without a
// matching output signs the constant 1, so one such signature fits any transaction. Below
// the transition height that stays as it is. From it the quirk is out of reach: such a
// signature lacks SIGHASH_FORKID, and with the flag the digest is a BIP143 one.
BOOST_AUTO_TEST_CASE(sighash_single_without_a_matching_output)
{
    CKey key;
    key.MakeNewKey(true);
    const std::vector<unsigned char> pubkey = ToByteVector(key.GetPubKey());
    const CMutableTransaction tx = MakeTwoInOneOut();
    const unsigned int n_in = 1; // no vout[1]
    const CScript checksig = CScript() << pubkey << OP_CHECKSIG;

    for (int hash_type : std::vector<int>{SIGHASH_SINGLE, SIGHASH_SINGLE | SIGHASH_ANYONECANPAY}) {
        BOOST_CHECK(SignatureHash(checksig, CTransaction(tx), n_in, hash_type, 0, SigVersion::BASE, nullptr) == uint256::ONE);
        const std::vector<unsigned char> sig_over_one = SignDigest(key, uint256::ONE, hash_type);
        BOOST_CHECK(Run(CScript() << sig_over_one, checksig, tx, n_in, false).ok);

        const ScriptResult r = Run(CScript() << sig_over_one, checksig, tx, n_in, true);
        BOOST_CHECK(!r.ok);
        BOOST_CHECK_EQUAL(r.err, SCRIPT_ERR_MUST_USE_FORKID);
        // The same signature with the flag added to its hash type byte: not a signature of this transaction.
        BOOST_CHECK(!Run(CScript() << SignDigest(key, uint256::ONE, hash_type | SIGHASH_FORKID), checksig, tx, n_in, true).ok);

        // A replay-protected SIGHASH_SINGLE signature for this input is an ordinary BIP143
        // signature (it commits to no output), as it has always been for SegWit v0 inputs.
        const PrecomputedTransactionData active = Regime(true);
        BOOST_CHECK(SignatureHash(checksig, CTransaction(tx), n_in, hash_type | SIGHASH_FORKID, 0, SigVersion::BASE, &active) != uint256::ONE);
        BOOST_CHECK(Run(CScript() << ValidSig(key, checksig, tx, n_in, hash_type, true), checksig, tx, n_in, true).ok);
    }
}

BOOST_AUTO_TEST_SUITE_END()
