# Makefile for test-dns-seeds utility
# Quick build without full autotools setup

CXX = g++
CXXFLAGS = -std=c++17 -O2 -Wall -Wextra -I. -Isrc -Isrc/secp256k1/include -Isrc/univalue/include -Isrc/libmw/include -DHAVE_CONFIG_H
LDFLAGS = -lpthread -lboost_system -lboost_filesystem -lboost_thread

# Source files needed
SOURCES = \
	src/test-dns-seeds.cpp \
	src/netbase.cpp \
	src/netaddress.cpp \
	src/chainparams.cpp \
	src/util/strencodings.cpp \
	src/util/system.cpp \
	src/util/time.cpp \
	src/logging.cpp \
	src/random.cpp \
	src/randomenv.cpp \
	src/util/threadnames.cpp \
	src/fs.cpp \
	src/sync.cpp \
	src/chainparamsbase.cpp \
	src/arith_uint256.cpp \
	src/uint256.cpp \
	src/hash.cpp \
	src/crypto/sha256.cpp \
	src/crypto/sha256_sse4.cpp \
	src/crypto/sha256_avx2.cpp \
	src/crypto/sha256_shani.cpp \
	src/crypto/sha3.cpp \
	src/crypto/hmac_sha512.cpp \
	src/crypto/hmac_sha256.cpp \
	src/crypto/sha512.cpp \
	src/crypto/ripemd160.cpp \
	src/crypto/rinhash.cpp \
	src/crypto/chacha20.cpp \
	src/crypto/blake3_impl.c \
	src/crypto/blake3_dispatch.c \
	src/crypto/blake3_portable.c \
	src/crypto/blake3.c \
	src/crypto/argon2/argon2.c \
	src/crypto/argon2/core.c \
	src/crypto/argon2/encoding.c \
	src/crypto/argon2/thread.c \
	src/crypto/argon2/blake2/blake2b.c \
	src/crypto/argon2/arch/x86_64/lib/argon2-arch.c \
	src/primitives/block.cpp \
	src/primitives/transaction.cpp \
	src/script/script.cpp \
	src/consensus/merkle.cpp \
	src/consensus/tx_check.cpp \
	src/util/settings.cpp \
	src/util/asmap.cpp \
	src/util/spanparsing.cpp \
	src/util/string.cpp \
	src/consensus/tx_verify.cpp \
	src/univalue/lib/univalue.cpp \
	src/univalue/lib/univalue_read.cpp \
	src/univalue/lib/univalue_write.cpp \
	src/support/cleanse.cpp \
	src/support/lockedpool.cpp

OBJECTS = $(SOURCES:.cpp=.o)

TARGET = test-dns-seeds

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS) $(TARGET)

.PHONY: all clean
