#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01, 0x04, 0x1F, 0xDC, 0x5D, 0x73, 0x25, 0x53, // 31.220.93.115:9555 - Community Forge EU1 mainnet seed node
    0x01, 0x04, 0x2E, 0xFA, 0xF8, 0x67, 0x25, 0x53, // 46.250.248.103:9555 - Community Forge JP2 mainnet seed node
    0x01, 0x04, 0x55, 0x11, 0xC0, 0x86, 0x25, 0x53  // 85.17.192.134:9555 - Community Forge NL3 mainnet seed node
};


static const uint8_t chainparams_seed_test[] = {
    0x01, 0x04, 0x1F, 0xDC, 0x5D, 0x73, 0x4C, 0x53, // 31.220.93.115:19555 - Community Forge EU1 testnet seed node
    0x01, 0x04, 0x2E, 0xFA, 0xF8, 0x67, 0x4C, 0x53, // 46.250.248.103:19555 - Community Forge JP2 testnet seed node
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H